const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const S={get(k,f){try{let v=localStorage.getItem(k);return v===null?f:JSON.parse(v)}catch{return f}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
const today=new Date().toISOString().slice(0,10);
const defaults={anchor:"Reset the kitchen before dinner.",tending:[{id:"1",text:"Start one load of laundry",done:false},{id:"2",text:"Water seedlings",done:false}],meals:{breakfast:"",lunch:"",dinner:"Chicken soup + sourdough",snacks:""},rhythm:[],special:0};
Object.entries(defaults).forEach(([k,v])=>{if(localStorage.getItem("g_"+k)===null)S.set("g_"+k,v)});
$('#dateLine').textContent=new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric'}).format(new Date());
const dlg=$('#dialog');$('#dialogClose').onclick=()=>dlg.close();
function modal(t,h,e="GATHERED"){$('#dialogTitle').textContent=t;$('#dialogEyebrow').textContent=e;$('#dialogBody').innerHTML=h;dlg.showModal()}
function nav(target){$$('.screen').forEach(x=>x.classList.toggle('active',x.dataset.screen===target));$$('[data-go]').forEach(x=>x.classList.toggle('active',x.dataset.go===target))}
$$('[data-go]').forEach(b=>b.onclick=()=>nav(b.dataset.go));
function mark(){let a=S.get('g_rhythm',[]);if(!a.includes(today)){a.push(today);S.set('g_rhythm',a)}rhythm()}
function key(d){return d.toISOString().slice(0,10)}
function rhythm(){let a=S.get('g_rhythm',[]),set=new Set(a),d=new Date();d.setHours(0,0,0,0);let streak=0;if(!set.has(key(d)))d.setDate(d.getDate()-1);while(set.has(key(d))){streak++;d.setDate(d.getDate()-1)}$('#rhythmCount').textContent=streak;let n=new Date(),p=`${n.getFullYear()}-${String(n.getMonth()+1).padStart(2,'0')}`;$('#monthCount').textContent=`${a.filter(x=>x.startsWith(p)).length} tended days this month`;let m=new Date(n),dow=(n.getDay()+6)%7;m.setDate(n.getDate()-dow);m.setHours(0,0,0,0);$('#weekDots').innerHTML=['M','T','W','T','F','S','S'].map((x,i)=>{let q=new Date(m);q.setDate(m.getDate()+i);let k=key(q);return `<div class="day-dot ${set.has(k)?'done':''} ${k===today?'today':''}"><span>${x}</span><i></i></div>`}).join('')}
function anchor(){$('#anchorText').textContent=S.get('g_anchor',defaults.anchor)}
$('#changeAnchorBtn').onclick=()=>{modal("Today's anchor",`<input id="ain" type="text" value="${ea(S.get('g_anchor',defaults.anchor))}"><button class="primary-button" id="asave">Save</button>`,"TODAY");setTimeout(()=>$('#asave').onclick=()=>{let v=$('#ain').value.trim();if(v){S.set('g_anchor',v);anchor();mark();dlg.close()}},0)}
function tasks(){let a=S.get('g_tending',defaults.tending);$('#todayTending').innerHTML=a.map(x=>`<div class="task-row ${x.done?'done':''}"><input data-check="${x.id}" type="checkbox" ${x.done?'checked':''}><div class="task-text">${esc(x.text)}</div><button class="task-menu" data-del="${x.id}">⋯</button></div>`).join('');$$('[data-check]').forEach(c=>c.onchange=()=>{let q=S.get('g_tending',[]),x=q.find(y=>y.id===c.dataset.check);x.done=c.checked;S.set('g_tending',q);mark();tasks()});$$('[data-del]').forEach(b=>b.onclick=()=>{let q=S.get('g_tending',[]),x=q.find(y=>y.id===b.dataset.del);modal("Tending item",`<input id="tin" type="text" value="${ea(x.text)}"><button class="primary-button" id="tedit">Save changes</button><button class="secondary-button" id="tdel">Delete</button>`,"TENDING");setTimeout(()=>{$('#tedit').onclick=()=>{x.text=$('#tin').value.trim()||x.text;S.set('g_tending',q);tasks();dlg.close()};$('#tdel').onclick=()=>{S.set('g_tending',q.filter(y=>y.id!==x.id));tasks();dlg.close()}},0)})}
$('#addTendingBtn').onclick=()=>{modal("Add something to tend",`<input id="newt" type="text" placeholder="Mop kitchen floor"><button class="primary-button" id="newts">Add to Today</button>`,"TENDING");setTimeout(()=>$('#newts').onclick=()=>{let v=$('#newt').value.trim();if(v){let a=S.get('g_tending',[]);a.push({id:String(Date.now()),text:v,done:false});S.set('g_tending',a);tasks();mark();dlg.close()}},0)}
function meals(){let m=S.get('g_meals',defaults.meals),r=[['Breakfast',m.breakfast],['Lunch',m.lunch],['Dinner',m.dinner],['Snacks',m.snacks]].filter(x=>x[1]);$('#mealSummary').innerHTML=r.map(x=>`<div class="meal-row"><div class="meal-label">${x[0]}</div><div>${esc(x[1])}</div></div>`).join('')}
$('#editMealsBtn').onclick=()=>{let m=S.get('g_meals',defaults.meals);modal("Today's meals",['breakfast','lunch','dinner','snacks'].map(k=>`<div class="field-label">${k}</div><input id="m_${k}" type="text" value="${ea(m[k])}">`).join('')+`<button class="primary-button" id="msave">Save meals</button>`,"MEALS");setTimeout(()=>$('#msave').onclick=()=>{let q={};['breakfast','lunch','dinner','snacks'].forEach(k=>q[k]=$('#m_'+k).value.trim());S.set('g_meals',q);meals();mark();dlg.close()},0)}
const waterHTML=()=>`<p class="dialog-copy">Your main shutoff controls water entering the whole house. Finding it before an emergency means you aren't searching while water is spreading.</p>
<div class="field-label">WHERE TO LOOK FIRST</div>
<div class="guide-step"><b>1. Where the service pipe enters the house</b>Follow the incoming water line. In colder climates, the valve is commonly indoors.</div>
<div class="guide-step"><b>2. Basement or foundation wall</b>Look along the wall facing the street or near the water meter.</div>
<div class="guide-step"><b>3. Utility area or crawl space</b>Check near other plumbing equipment or the point where the main line comes through the foundation.</div>
<div class="guide-step"><b>4. Near the water meter</b>The house-side shutoff is often close to the meter. Avoid utility-owned valves you aren't sure about.</div>
<div class="field-label">WHAT IT MAY LOOK LIKE</div>
<div class="visual-guide"><div class="valve-visual"><b>Gate valve</b><div class="pipe"><div class="wheel"></div></div><span class="tiny">Round wheel · older/common style</span></div><div class="valve-visual"><b>Ball valve</b><div class="pipe"><div class="lever"></div></div><span class="tiny">Straight lever · quarter-turn style</span></div></div>
<div class="warning"><b>Don't force a stuck valve.</b> If it is corroded, leaking, unfamiliar, or takes excessive force, stop and get help from a plumber or water utility.</div>
<div class="field-label">SAVE YOUR LOCATION</div><input id="waterLoc" type="text" value="${ea(S.get('g_water_location',''))}" placeholder="Example: basement, front wall beside meter"><button class="primary-button" id="saveWater">Save to my home</button>`;
function waterGuide(){modal("Find your main water shutoff",waterHTML(),"HOME STEWARDSHIP");setTimeout(()=>$('#saveWater').onclick=()=>{S.set('g_water_location',$('#waterLoc').value.trim());mark();$('#saveWater').textContent="Saved ✓"},0)}
$('#stewardshipCard').onclick=waterGuide;$('#openWaterGuide').onclick=waterGuide;
$('#scriptureCard').onclick=()=>{nav('faith');faithTab('history')};
const history=[['Today','Colossians 3:23','Faithfulness in ordinary work matters too.'],['Yesterday','Psalm 90:17','Ask God to establish the work of your hands.'],['2 days ago','Matthew 6:34','Receive today without carrying tomorrow all at once.'],['3 days ago','Proverbs 31:27','Attentiveness to the household can be an act of care.']];
function faithTab(t){$$('[data-faith-tab]').forEach(b=>b.classList.toggle('selected',b.dataset.faithTab===t));let el=$('#faithContent');if(t==='history')el.innerHTML=history.map(x=>`<div class="history-item"><div class="tiny">${x[0]}</div><strong>${x[1]}</strong><p class="muted small">${x[2]}</p></div>`).join('');if(t==='reader')reader();if(t==='notes')notes();if(t==='lessons')el.innerHTML=`<div class="lesson-card"><div class="section-label">MINI STUDY</div><h3>Faithfulness in ordinary work</h3><p class="muted small">Read Colossians 3:12–24. Notice how Paul connects everyday relationships and work with serving Christ.</p><button class="text-button no-pad" id="lessonNote">Write a reflection</button></div><div class="lesson-card"><div class="section-label">COMING LATER</div><h3>Guided Bible studies</h3><p class="muted small">Saved studies, reading plans, questions, and connections to your Commonplace.</p></div>`}
$$('[data-faith-tab]').forEach(b=>b.onclick=()=>faithTab(b.dataset.faithTab));
const chapters={Colossians:{3:["If then you were raised together with Christ, seek the things that are above, where Christ is, seated on the right hand of God.","Set your mind on the things that are above, not on the things that are on the earth.","For you died, and your life is hidden with Christ in God.","When Christ, our life, is revealed, then you will also be revealed with him in glory.","Put to death therefore your members which are on the earth: sexual immorality, uncleanness, depraved passion, evil desire, and covetousness, which is idolatry.","For these things’ sake the wrath of God comes on the children of disobedience.","You also once walked in those, when you lived in them.","But now you also put them all away: anger, wrath, malice, slander, and shameful speaking out of your mouth.","Don’t lie to one another, seeing that you have put off the old man with his doings,","and have put on the new man, who is being renewed in knowledge after the image of his Creator,","where there can’t be Greek and Jew, circumcision and uncircumcision, barbarian, Scythian, bondservant, freeman; but Christ is all, and in all.","Put on therefore, as God’s chosen ones, holy and beloved, a heart of compassion, kindness, lowliness, humility, and perseverance;","bearing with one another, and forgiving each other, if any man has a complaint against any; even as Christ forgave you, so you also do.","Above all these things, walk in love, which is the bond of perfection.","And let the peace of God rule in your hearts, to which also you were called in one body, and be thankful.","Let the word of Christ dwell in you richly; in all wisdom teaching and admonishing one another with psalms, hymns, and spiritual songs, singing with grace in your heart to the Lord.","Whatever you do, in word or in deed, do all in the name of the Lord Jesus, giving thanks to God the Father, through him.","Wives, be in subjection to your husbands, as is fitting in the Lord.","Husbands, love your wives, and don’t be bitter against them.","Children, obey your parents in all things, for this pleases the Lord.","Fathers, don’t provoke your children, so that they won’t be discouraged.","Servants, obey in all things those who are your masters according to the flesh, not just when they are looking, as men pleasers, but in singleness of heart, fearing God.","And whatever you do, work heartily, as for the Lord, and not for men,","knowing that from the Lord you will receive the reward of the inheritance; for you serve the Lord Christ.","But he who does wrong will receive again for the wrong that he has done, and there is no partiality."]}};
function reader(){let verses=chapters.Colossians[3],hi=S.get('g_bible_highlights',[]);$('#faithContent').innerHTML=`<div class="bible-controls"><select id="bookSel"><option>Colossians</option></select><select id="chapSel"><option>3</option></select></div><div class="bible-text">${verses.map((v,i)=>`<div class="verse-line ${hi.includes(i+1)?'highlighted':''}" data-verse="${i+1}"><span class="verse-num">${i+1}</span>${esc(v)}</div>`).join('')}</div><p class="tiny">Tap a verse to highlight it. World English Bible text.</p>`;$$('[data-verse]').forEach(v=>v.onclick=()=>{let a=S.get('g_bible_highlights',[]),n=+v.dataset.verse;a=a.includes(n)?a.filter(x=>x!==n):[...a,n];S.set('g_bible_highlights',a);reader();mark()})}
function notes(){let note=S.get('g_scripture_note',''),hi=S.get('g_bible_highlights',[]);$('#faithContent').innerHTML=`<div class="note-item"><strong>Colossians 3:23 note</strong><textarea id="faithNote" placeholder="What stands out to you?">${esc(note)}</textarea><button class="primary-button" id="saveFaithNote">Save note</button></div><div class="note-item"><strong>Highlighted in Colossians 3</strong><p class="muted small">${hi.length?hi.map(x=>'v.'+x).join(', '):'No highlights yet.'}</p></div>`;setTimeout(()=>$('#saveFaithNote').onclick=()=>{S.set('g_scripture_note',$('#faithNote').value);mark();$('#saveFaithNote').textContent='Saved ✓'},0)}
$('#highlightToday').onclick=()=>{let a=S.get('g_bible_highlights',[]);if(!a.includes(23))a.push(23);S.set('g_bible_highlights',a);mark();$('#highlightToday').textContent='Highlighted ✓'};
$('#noteToday').onclick=()=>faithTab('notes');
$('#simplifyBtn').onclick=()=>modal("What kind of day is it?",`<div class="action-row" style="flex-wrap:wrap">${['Normal','Busy','Low Energy','Sick','Outing'].map(x=>`<button class="pill" data-mode="${x}">${x}</button>`).join('')}</div><p class="dialog-copy">Choose the amount of life you have capacity for today. Gathered will eventually adapt what it surfaces.</p>`,"SIMPLIFY TODAY");
$('#resetBtn').onclick=()=>modal("10-minute reset",`<p class="dialog-copy">Gather dishes · clear obvious clutter · start one load · wipe counters · reset the living room.</p><button class="primary-button" id="resetDone">I tended the room</button>`,"RESET");
setTimeout(()=>{},0);
$('#newSpecialBtn').onclick=()=>{let a=["Slice peaches after dinner and eat them outside.","Light a candle at dinner tonight.","Put on music during the evening reset.","Take five minutes outside before sunset."],i=(S.get('g_special',0)+1)%a.length;S.set('g_special',i);$('#specialIdea').textContent=a[i]};
$('#specialIdea').textContent=["Slice peaches after dinner and eat them outside.","Light a candle at dinner tonight.","Put on music during the evening reset.","Take five minutes outside before sunset."][S.get('g_special',0)%4];
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function ea(v=''){return esc(v)}
function render(){rhythm();anchor();tasks();meals()}render();