const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const S={g(k,f){try{const v=localStorage.getItem(k);return v===null?f:JSON.parse(v)}catch{return f}},s(k,v){localStorage.setItem(k,JSON.stringify(v))}};
const defaults={anchor:"Reset the kitchen before dinner.",tasks:[{id:1,text:"Start one load of laundry",done:false},{id:2,text:"Water seedlings",done:false}],dinner:"Chicken soup + sourdough",rhythm:[],reset:{},water:"",note:"",highlights:[]};
Object.entries(defaults).forEach(([k,v])=>{if(localStorage.getItem("g2_"+k)===null)S.s("g2_"+k,v)});
$('#dateLine').textContent=new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric'}).format(new Date());
function nav(t){$$('.screen').forEach(x=>x.classList.toggle('active',x.dataset.screen===t));$$('[data-go]').forEach(x=>x.classList.toggle('active',x.dataset.go===t));}
$$('[data-go]').forEach(b=>b.onclick=()=>nav(b.dataset.go));
const sheet=$('#sheet');$('#closeSheet').onclick=()=>sheet.close();
function openSheet(html){$('#sheetBody').innerHTML=html;sheet.showModal()}
function todayKey(){return new Date().toISOString().slice(0,10)}
function markRhythm(){let a=S.g('g2_rhythm',[]),t=todayKey();if(!a.includes(t)){a.push(t);S.s('g2_rhythm',a)}renderRhythm()}
function renderRhythm(){let a=S.g('g2_rhythm',[]),set=new Set(a),n=new Date(),m=new Date(n),dow=(n.getDay()+6)%7;m.setDate(n.getDate()-dow);m.setHours(0,0,0,0);let week=0;$('#rhythmWeek').innerHTML=['M','T','W','T','F','S','S'].map((d,i)=>{let q=new Date(m);q.setDate(m.getDate()+i);let k=q.toISOString().slice(0,10),done=set.has(k);if(done)week++;return `<div class="rhythm-day ${done?'done':''}">${d}<span></span></div>`}).join('');$('#rhythmText').textContent=`${week} days in rhythm this week`;let p=`${n.getFullYear()}-${String(n.getMonth()+1).padStart(2,'0')}`;$('#monthText').textContent=`${a.filter(x=>x.startsWith(p)).length} tended this month`;}
function renderToday(){let a=S.g('g2_anchor',defaults.anchor);$('#anchorText').innerHTML=esc(a).replace(' before dinner.','<br>before dinner.');let tasks=S.g('g2_tasks',defaults.tasks),done=tasks.filter(x=>x.done).length;$('#tendingSummary').textContent=`${done} of ${tasks.length} tasks done`;$('#dinnerText').textContent=S.g('g2_dinner',defaults.dinner);renderRhythm()}
$('#changeAnchorBtn').onclick=()=>openSheet(`<div class="eyebrow">TODAY'S FOCUS</div><h2>What matters most today?</h2><input id="anchorIn" value="${ea(S.g('g2_anchor',defaults.anchor))}"><button class="cta" id="anchorSave">Save focus</button>`);
document.addEventListener('click',e=>{if(e.target.id==='anchorSave'){S.s('g2_anchor',$('#anchorIn').value.trim()||defaults.anchor);markRhythm();renderToday();sheet.close()}});
$('#openTending').onclick=()=>{let t=S.g('g2_tasks',defaults.tasks);openSheet(`<div class="eyebrow">TENDING</div><h2>Today's tending</h2><div class="checklist">${t.map(x=>`<label class="checkitem"><input type="checkbox" data-task="${x.id}" ${x.done?'checked':''}><span>${esc(x.text)}</span></label>`).join('')}</div><input id="newTask" placeholder="Add something small"><button class="cta" id="addTask">Add to today</button>`)}
document.addEventListener('change',e=>{if(e.target.dataset.task){let t=S.g('g2_tasks',defaults.tasks),x=t.find(v=>String(v.id)===e.target.dataset.task);if(x)x.done=e.target.checked;S.s('g2_tasks',t);markRhythm();renderToday()}});
document.addEventListener('click',e=>{if(e.target.id==='addTask'){let v=$('#newTask').value.trim();if(v){let t=S.g('g2_tasks',defaults.tasks);t.push({id:Date.now(),text:v,done:false});S.s('g2_tasks',t);markRhythm();renderToday();sheet.close();$('#openTending').click()}}});
$('#openDinner').onclick=()=>openSheet(`<div class="eyebrow">DINNER</div><h2>What's for dinner?</h2><input id="dinnerIn" value="${ea(S.g('g2_dinner',defaults.dinner))}"><button class="cta" id="saveDinner">Save dinner</button>`);
document.addEventListener('click',e=>{if(e.target.id==='saveDinner'){S.s('g2_dinner',$('#dinnerIn').value.trim());markRhythm();renderToday();sheet.close()}});
$('#resetBtn').onclick=()=>{let s=S.g('g2_reset',{}),items=['Gather dishes','Clear counters','Start one load (laundry or dishwasher)','Wipe counters','Reset the living area'],done=Object.values(s).filter(Boolean).length;openSheet(`<div class="eyebrow">10-MINUTE RESET</div><h2>Kitchen Reset</h2><p class="source">Just 10 minutes to make tomorrow easier.</p><div class="checklist">${items.map((x,i)=>`<label class="checkitem"><input data-reset="${i}" type="checkbox" ${s[i]?'checked':''}><span>${x}</span></label>`).join('')}</div><div class="progress"><span style="width:${done/5*100}%"></span></div><div class="center source">${done} of 5</div><button class="cta" id="resetComplete">I tended this room</button>`)}
document.addEventListener('change',e=>{if(e.target.dataset.reset!==undefined){let s=S.g('g2_reset',{});s[e.target.dataset.reset]=e.target.checked;S.s('g2_reset',s);markRhythm();$('#resetBtn').click()}});
document.addEventListener('click',e=>{if(e.target.id==='resetComplete'){markRhythm();sheet.close()}});
$('#openScripture').onclick=()=>nav('faith');$('#readChapter').onclick=()=>{nav('reader');renderBible()};$('#readerNotes').onclick=()=>nav('faith');
const verses=["If then you were raised together with Christ, seek the things that are above, where Christ is, seated on the right hand of God.","Set your mind on the things that are above, not on the things that are on the earth.","For you died, and your life is hidden with Christ in God.","When Christ, our life, is revealed, then you will also be revealed with him in glory.","Put to death therefore your members which are on the earth: sexual immorality, uncleanness, depraved passion, evil desire, and covetousness, which is idolatry.","For these things’ sake the wrath of God comes on the children of disobedience.","You also once walked in those, when you lived in them."];
function renderBible(){let h=S.g('g2_highlights',[]);$('#bibleReader').innerHTML=verses.map((v,i)=>`<div class="verse-line ${h.includes(i+1)?'highlighted':''}" data-verse="${i+1}"><span class="verse-num">${i+1}</span>${esc(v)}</div>`).join('')}
document.addEventListener('click',e=>{if(e.target.closest('[data-verse]')){let el=e.target.closest('[data-verse]'),n=+el.dataset.verse,h=S.g('g2_highlights',[]);h=h.includes(n)?h.filter(x=>x!==n):[...h,n];S.s('g2_highlights',h);markRhythm();renderBible()}});
$('#highlightBtn').onclick=()=>{let h=S.g('g2_highlights',[]);if(!h.includes(23))h.push(23);S.s('g2_highlights',h);markRhythm();$('#highlightBtn small').textContent='Highlighted'};
function noteSheet(){openSheet(`<div class="eyebrow">SCRIPTURE NOTE</div><h2>Colossians 3:23</h2><textarea id="noteIn" placeholder="What stands out to you?">${esc(S.g('g2_note',''))}</textarea><button class="cta" id="saveNote">Save note</button>`)}
$('#noteBtn').onclick=noteSheet;$('#myNotes').onclick=noteSheet;$('#reflectBtn').onclick=noteSheet;
document.addEventListener('click',e=>{if(e.target.id==='saveNote'){S.s('g2_note',$('#noteIn').value);markRhythm();sheet.close()}});
$('#previousScriptures').onclick=()=>openSheet(`<div class="eyebrow">PREVIOUS SCRIPTURES</div><h2>Your daily journey</h2><div class="checklist"><div class="checkitem">Today · Colossians 3:23</div><div class="checkitem">Yesterday · Psalm 90:17</div><div class="checkitem">2 days ago · Matthew 6:34</div><div class="checkitem">3 days ago · Proverbs 31:27</div></div>`);
$('#bibleLessons').onclick=()=>openSheet(`<div class="eyebrow">BIBLE LESSON</div><h2>Faithfulness in ordinary work</h2><p class="source">Read Colossians 3:12–24 and notice how Paul connects everyday relationships and work with serving Christ.</p>`);
function waterGuide(){nav('household')}
$('#openStewardship').onclick=waterGuide;
$('#foundMine').onclick=()=>openSheet(`<div class="center"><div style="font-size:44px;color:var(--sage)">✓</div><h2>Great! Save its location</h2><p class="source">This helps you (and your family) find it quickly.</p></div><label class="eyebrow">WHERE IS IT LOCATED?</label><input id="waterLoc" value="${ea(S.g('g2_water',''))}" placeholder="Basement, front wall"><label class="eyebrow">ANY NOTES?</label><textarea id="waterNote" placeholder="Behind shelving next to the water meter."></textarea><div class="photo-box">📷 Take a photo</div><button class="cta" id="saveWater">Save location</button><button class="subtle-btn" onclick="document.getElementById('sheet').close()">Not now</button>`);
document.addEventListener('click',e=>{if(e.target.id==='saveWater'){S.s('g2_water',$('#waterLoc').value.trim());markRhythm();sheet.close()}});
$('#cantFind').onclick=()=>openSheet(`<div class="eyebrow">STILL LOOKING?</div><h2>Try these next</h2><div class="checklist"><div class="checkitem">Follow the incoming water pipe from the foundation inward.</div><div class="checkitem">Look near the meter or utility equipment.</div><div class="checkitem">Check any crawlspace access near where the service line enters.</div><div class="checkitem">Call your water utility or a licensed plumber if you're unsure.</div></div>`);
$('#quickAdd').onclick=()=>openSheet(`<div class="eyebrow">QUICK ADD</div><h2>Get it out of your head.</h2><input id="quickIn" placeholder="Something to remember..."><button class="cta" id="quickSave">Save to tending</button>`);
document.addEventListener('click',e=>{if(e.target.id==='quickSave'){let v=$('#quickIn').value.trim();if(v){let t=S.g('g2_tasks',defaults.tasks);t.push({id:Date.now(),text:v,done:false});S.s('g2_tasks',t);markRhythm();renderToday();sheet.close()}}});
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function ea(v=''){return esc(v)}
renderToday();