const app=document.querySelector("#app"), sheet=document.querySelector("#sheet");
const S={tasks:["Start one load of laundry","Water seedlings","Pray"],reset:["Gather dishes","Clear counters","Start one load (laundry or dishwasher)","Wipe counters","Reset the living area"]};
function shell(x){app.innerHTML=x; window.scrollTo(0,0)}
function today(){shell(`<div class="eyebrow">Gathered</div><h1>Good morning,<br>Emi</h1><p class="muted">Thursday, August 20</p>
<div class="card"><div class="eyebrow">Gathered rhythm</div><div class="rhythm">${["M","T","W","T","F","S","S"].map((d,i)=>`<div class="day ${i==3?"active":""}">${d}<i></i></div>`).join("")}</div><p class="muted">1 day in rhythm this week · 1 tended this month</p></div>
<div class="card soft"><div class="eyebrow">Today's focus</div><h2>Reset the living room before I leave</h2><div class="row"><span class="pill">◷ 10 min</span><button class="link" onclick="resetSheet()">Start reset</button></div></div>
<div class="eyebrow section">Today at a glance</div><div class="card glance">
<div class="item row" onclick="tendingSheet()"><span>✓ &nbsp; Tending</span><small class="muted">0 of 3 ›</small></div>
<div class="item row"><span>♨ &nbsp; Dinner</span><small class="muted">Chicken soup + sourdough</small></div>
<div class="item row" onclick="bible()"><span>✦ &nbsp; For your heart</span><small class="muted">Colossians 3:23 ›</small></div></div>`);active("today")}
function household(){shell(`<div class="eyebrow">Gathered</div><h1>Household</h1><h2 class="muted" style="font-size:30px">The practical side of tending home & family.</h2>
<div class="row section"><div class="eyebrow">Our family</div><button class="link">View all ›</button></div><div class="family">${[["E","Emi"],["D","David"],["C","Clayton"],["L","Levi"]].map(p=>`<div class="person" onclick="${p[1]=="Clayton"?"clayton()":""}"><div class="avatar">${p[0]}</div><p>${p[1]}</p></div>`).join("")}</div>
<div class="eyebrow section">Household areas</div><div class="areas">
<div class="card area" onclick="homeArea()"><div class="card-title">Home</div><p>Repairs, projects, maintenance & systems</p></div>
<div class="card area" onclick="cleaning()"><div class="card-title">Cleaning & Resets</div><p>Daily, weekly, monthly & seasonal</p></div>
<div class="card area" onclick="familyArea()"><div class="card-title">Family</div><p>Profiles, notes, milestones & care</p></div>
<div class="card area"><div class="card-title">Household Rhythm</div><p>Routines, recurring tasks & shared life</p></div></div>`);active("household")}
function homeArea(){sub("Home","Repairs, projects, maintenance & systems",["Stewardship & home knowledge","Rooms","Systems & appliances","Projects","Home reference","History"])}
function cleaning(){sub("Cleaning & Resets","A calm home rhythm—not a scorecard.",["Daily reset","Weekly cleaning","Monthly deep clean","Seasonal reset"])}
function familyArea(){shell(`<button class="back" onclick="household()">‹ Household</button><div class="eyebrow">Family</div><h1>Our people.</h1><p class="muted">A home for the details that help you care for each person well.</p>${["Emi","David","Clayton","Levi"].map(n=>`<div class="card row" onclick="${n=="Clayton"?"clayton()":""}"><h2>${n}</h2><span>›</span></div>`).join("")}`)}
function clayton(){shell(`<button class="back" onclick="familyArea()">‹ Family</button><div class="eyebrow">Clayton</div><h1>Growing & Learning</h1><p class="muted">Development, learning & homeschool—organized around growth rather than pressure.</p>
<div class="card soft"><div class="eyebrow">Right now</div><h2>What we're noticing</h2><p class="muted">Save strengths, new interests, questions and things you want to watch over time.</p></div>
${["Learning goals","Age-appropriate lessons","Milestones & development","Observations & concerns","Books & resources","Learning record"].map(x=>`<div class="card row"><h2 style="font-size:25px">${x}</h2><span>›</span></div>`).join("")}`)}
function sub(title,desc,items){shell(`<button class="back" onclick="household()">‹ Household</button><div class="eyebrow">Household</div><h1>${title}</h1><p class="muted">${desc}</p>${items.map(x=>`<div class="card row"><h2 style="font-size:25px">${x}</h2><span>›</span></div>`).join("")}`)}
function bible(){shell(`<button class="back" onclick="today()">‹ Today</button><div class="eyebrow">Faith & Bible</div><h1>Stay in the Word.</h1><div class="eyebrow">Today's scripture</div><h2>Colossians 3:23</h2><p class="scripture">Whatever you do, work heartily, as for the Lord, and not for men.</p><p class="muted">World English Bible · public domain</p><p><span class="pill">Highlight</span><span class="pill">Add note</span></p><div class="card"><div class="eyebrow">Daily scriptures</div><h2>Yesterday · Psalm 90:17</h2><p class="muted">Ask God to establish the work of your hands.</p><h2>2 days ago · Matthew 6:34</h2><p class="muted">Receive today without carrying tomorrow all at once.</p></div>`)}
function tendingSheet(){openSheet("Today's tending","Only what matters today",S.tasks)}
function resetSheet(){openSheet("Kitchen Reset","Just 10 minutes to make tomorrow easier.",S.reset)}
function openSheet(title,desc,items){sheet.classList.remove("hidden");sheet.innerHTML=`<div class="sheet"><div class="row"><div><div class="eyebrow">${title.includes("Reset")?"10-minute reset":"Tending"}</div><h1 style="font-size:43px">${title}</h1></div><button onclick="closeSheet()" style="border:0;background:none;font-size:35px">×</button></div><p class="muted">${desc}</p>${items.map(x=>`<label class="check"><input type="checkbox"><span class="serif" style="font-size:23px">${x}</span></label>`).join("")}<button class="primary" style="width:100%;margin-top:25px" onclick="closeSheet()">I tended this</button></div>`}
function closeSheet(){sheet.classList.add("hidden")}
function commonplace(){shell(`<div class="eyebrow">Gathered</div><h1>Commonplace</h1><p class="muted">A quiet place to keep what you don't want to lose.</p><div class="card"><h2>Notes & things to remember</h2><p class="muted">This area is ready for the next build.</p></div>`);active("commonplace")}
function seasonal(){shell(`<div class="eyebrow">Gathered</div><h1>Seasonal</h1><p class="muted">Garden, home, traditions and the work of the season.</p><div class="card"><h2>Late summer</h2><p class="muted">This area is ready for the next build.</p></div>`);active("seasonal")}
function active(s){document.querySelectorAll(".nav [data-screen]").forEach(b=>b.classList.toggle("active",b.dataset.screen==s))}
document.querySelectorAll(".nav [data-screen]").forEach(b=>b.onclick=()=>({today,commonplace,seasonal,household}[b.dataset.screen]()))
document.querySelector("#quick").onclick=()=>openSheet("Quick add","Capture something without leaving what you're doing.",["Add a task","Add a note","Add an event"])
today();